= Everything You Need to know To Add Redux To Your Project

Do you find you are passing a large state object from one part of your project
to another? Are you using React and find yourself doing an excessive amount
of prop-drilling?

It is probably time to consider a better way to manage your state. Enter Redux.It's
tried and true. Are there downsides to it? Certainly, but nothing is perfect
and the advantages are hefty.

== The Setup

Alright so enough sales pitch, let's get started.
Of course, Redux can be used but for our purposes we will be adding Redux to a React application.

Open your terminal and navigate to the place where your project will be live.
Enter the following command...

    npx create-react-app learningRedux

Once this has finished its process cd to the root folder where the `package.json` file is located.
Then run the following commands for either npm or yarn.

    npm install redux react-redux

    yarn install redux react- redux


== React Create Store
//add store to index.js
The first task that we have is to create our store in index.js.

[source, javascript]
----
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import registerServiceWorker from './registerServiceWorker';
import {Provider} from "react-redux";

const store = createStore(reducer);
ReactDOM.render(<Provider store={store}><App /></Provider>, document.getElementById('root'));
registerServiceWorker();
----

//folder structure
//create reducer
//wrap App tag with Provider
// add actions
//access store in a component
// connect function ** need to dive deeper to understand what this is doing
// dispatch action from component
// dispatch action from nested component

